# Generated by Django 4.1.3 on 2023-02-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_in_time_alter_staff_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='in_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='out_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
