# Generated by Django 4.1.3 on 2023-03-01 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_attendancelogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelogs',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
