# Generated by Django 4.1.3 on 2023-03-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_attendancelogs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='money',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
    ]
