# Generated by Django 4.1.3 on 2023-03-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_moneylogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneylogs',
            name='details',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
